apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-local-cert
  namespace: default
spec:
  commonName: wordpress
  dnsNames:
    - wordpress
  secretName: wordpress-local-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  usages:
    - digital signature
    - key encipherment


